name: Deploy Hexo Site

on:
  push:
    branches:
      - master # Set a branch to trigger deployment
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # This depth parameter is optional - fetching the full history can improve the accuracy of the GH Pages deployment action's change detection.
        # However, it can also increase the time required for the checkout step to complete.
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your Node.js version here

    - name: Install Dependencies
      run: npm install

    - name: Install Hexo
      run: npm install -g hexo-cli

    - name: Billd
      run: bash ./build.sh

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto Commit
        branch: ${{ github.head_ref }}
        file_pattern: data.csv

    - name: Deploying
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        
